### ISSUE TITLE
[BUG] Random error on Export

### ISSUE THREAD

**Issue by Andre601** [LoneDev6/itemsadder-entity#1]
**Describe the bug**
A random error appeared during the export process.
While I do not know what the issue may be, my guess is, that the plugin doesn't handle timelines with no final keyframe very well...

**To Reproduce**
This is only a guess what the cause is...

1. Create an animation
2. Add keyframes
3. Make sure the timeline has no keyframe at the very end
4. Export model

**Expected behavior**
Export should work fine

**Error Message**
```
------ Error ------
[object Object]  //  "Time to fire up the ol' debugger!"
------ Stack ------
Error
    at Ld (<anonymous>:234:42495)
    at <anonymous>:234:238829
    at <anonymous>:234:238994

Build ID: local-24837f47a5998ff5f420d06410af8fbe955dc1907d761b12336c16da182721bc
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10 Pro

**Additional context**

**Comment by LoneDev6** [comment]
Please attach the project file, thanks

**Comment by ExoSeamoth** [comment]
I'm sorry I didn't do it right away.
[ship.zip](https://github.com/LoneDev6/itemsadder-entity/files/9471327/ship.zip)

**Comment by LoneDev6** [comment]
Thanks, I'll check this as soon as I can

**Comment by LoneDev6** [comment]
There is something wrong with your model and I cannot identify it.
Somehow some parts of the model have missing properties, probably caused by some other blockbench extensions.

It also contains multiple misconfigurations. Every single bone have a limit, you have a lot of boxes outside of this limit.
Refer to the red box.

![image](https://user-images.githubusercontent.com/27242001/229838783-741c66a4-c26d-4d1b-86a8-2b3fb8e4bf88.png)


Also for some reason you set max scaling instead of max model size.
This made the red boxes even smaller. If you don't need to animate scaling of your model you must always set "max model size" to allow bigger models.

![image](https://user-images.githubusercontent.com/27242001/229841250-c4eec898-563b-4cb3-a701-4d63b582efba.png)


## Fixed it for you
[ship_fixed.zip](https://github.com/LoneDev6/itemsadder-entity/files/11150254/ship_fixed.zip)


https://user-images.githubusercontent.com/27242001/229841784-0f54c1a8-7866-47af-b92b-a30789ffae4c.mp4

**Comment by LoneDev6** [comment]
> A random error appeared during the export process.
While I do not know what the issue may be, my guess is, that the plugin doesn't handle timelines with no final keyframe very well...

I have no idea how to trigger this, works fine for models I made
