### ISSUE TITLE
convert problem

### ISSUE THREAD

**Issue by MusicTW** [LoneDev6/itemsadder-entity#21]
before convert
![image](https://github.com/LoneDev6/itemsadder-entity/assets/52475422/1cae072f-77f2-49fa-a9ff-cc99a78f1f64)
after convert
![image](https://github.com/LoneDev6/itemsadder-entity/assets/52475422/47e02090-b140-4429-8729-618de7aca661)
most of the cubes r rotated.

**Comment by LoneDev6** [comment]
Attach your model file.
This extension was tested with more than 20 models made by various artists and the blocks rotations are untouched

**Comment by MusicTW** [comment]
[crab_1.zip](https://github.com/LoneDev6/itemsadder-entity/files/12774978/crab_1.zip)

**Comment by LoneDev6** [comment]
This happens because you rotated the cubes and not the bones.
Cubes can't have cube rotated in such a way that the game items can't be rotated.

For example if you had created the crab directly as iaentitymodel you would have received this error on export:
![image](https://github.com/LoneDev6/itemsadder-entity/assets/27242001/f94ee552-8e13-48e9-8a8c-011b8891ed0b)


What you have to do is use a single bone for each one of your cubes instead of using multiple cubes on a single bone.

I fixed the model for you, the only thing left to fix are the legs animations.
[crab_1_fixed.zip](https://github.com/LoneDev6/itemsadder-entity/files/12834526/crab_1_fixed.zip)
